name: Publish

on:
  push:
    branches:
      - "eduTools"

jobs:
  release_assets:
    name: Release assets
    runs-on: ${{ matrix.config.os }} # we run many different builds
    strategy:
      # just an example matrix
      matrix:
        config:
          - os: ubuntu-18.04
          - os: macos-10.15
          - os: windows-latest
    steps:
      # checkout of cource
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          dir: '${{ github.workspace }}'
      - name: Start SSH session
        uses: luchihoratiu/debug-via-ssh@main
        if: matrix.config.os == 'windows-latest'
        with:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
      - name: "Build (linux)"
        run: cd distributions; sudo ./build-debian-package-auto.sh; zip -r ../deploy/jamulus.zip ../*.deb
        if: matrix.config.os == 'ubuntu-18.04'
      - name: "Build (Windows)"
        run: powershell .\windows\deploy_windows.ps1 ${{ github.workspace }}\Qt\5.15.2\
        if: matrix.config.os == 'windows-latest'

        
